#!/usr/bin/env sh
      rm -f "/usr/local/bin/Basement"
      rm -f "/usr/local/bin/BasementGHT.idd"
      rm -f "/usr/local/bin/convertESOMTR"
      rm -f "/usr/local/bin/EnergyPlus"
      rm -f "/usr/local/bin/Energy+.idd"
      rm -f "/usr/local/bin/EP-Compare"
      rm -f "/usr/local/bin/EPMacro"
      rm -f "/usr/local/bin/ExpandObjects"
      rm -f "/usr/local/bin/HVAC-Diagram"
      rm -f "/usr/local/bin/IDFVersionUpdater"
      rm -f "/usr/local/bin/parametricpreprocessor"
      rm -f "/usr/local/bin/parser"
      rm -f "/usr/local/bin/ReadVarsESO"
      rm -f "/usr/local/bin/runenergyplus"
      rm -f "/usr/local/bin/runepmacro"
      rm -f "/usr/local/bin/runreadvars"
      rm -f "/usr/local/bin/Slab"
      rm -f "/usr/local/bin/SlabGHT.idd"
      rm -f "/usr/local/bin/Transition-V8-2-0-to-V8-3-0"
      rm -f "/usr/local/bin/V8-2-0-Energy+.idd"
      rm -f "/usr/local/bin/V8-3-0-Energy+.idd"
      rm -f /usr/local/share/man/man1/energyplus.1
echo "Symbolic links to this installation of EnergyPlus have been removed."
echo "You may remove the EnergyPlus directory to completely uninstall the software."
